[project]
name = "TweetNaCl"
package = "tiannian"
version = "0.1.0"
maintainer = "tiannian"
upstream = "https://github.com/karma-iot/TweetNaCl"
platform = [ "general" ]
arch = [ "general" ]

[dependencies]
